CREATE TABLE VERSIONS
(
  ID integer NOT NULL,
  "VERSION" varchar(10) NOT NULL,
  INSTALLATIONDATE timestamp NOT NULL,
  PRODUCT varchar(255) NOT NULL,
  CONSTRAINT VERSIONS_PK PRIMARY KEY (ID)
);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON VERSIONS TO  SYSDBA WITH GRANT OPTION;

GRANT SELECT
 ON VERSIONS TO  THEDOCTORWHO;




